### ISSUE TITLE
2-4 애플리케이션 설정

### ISSUE THREAD

**Issue by jongfeel** [jongfeel/BookReview#294]
#### 설정 값 설정하기

org.springframework.beans.factory.annotation.Value 를 사용, 스프링 표현 언어 쿼리를 써서 설정 값을 사용

```
package com.microservices.chapter2

import org.springframework.beans.factory.annotation.Value
import org.springframework.stereotype.Service

@Service
class ExampleService : ServiceInterface {
    @Value(value = "\${service.message.text}")
    private lateinit var text: String

    override fun getHello(name: String) = "$text $name"
}
```

\$ 는 스프링에서 사용하는 리터럴 문자열
$ 는 코틀린 컴파일러가 인라인 문자열로 인식

##### 프로퍼티 사용하기

application.properties 에서 다음과 같이 사용

```
SERVICE.MESSAGE.TEXT="hello"
```

프로퍼티는 일반적으로 대문자 사용, 하지만 스프링에서는 대/소문자를 가리지 않고 소문자로만 참조해서 설정 값을 가져옴

##### Yaml 사용

application.properties에서 application.yml로 바꾸고 다음과 같이 사용

```
service:
  message:
    text: "hello"
```

복잡한 구성에서 중복을 방지하고 사용할 수 있는 방법, 책에서는 이 방법을 사용

##### 명령줄 인수 사용

기존 설정 값을 덮어쓰고 명령줄 인수를 사용할 수 있다.

``` shell
java -jar target/chapter2-0.0.1-SNAPSHOT.jar --service.message.text="other hello"
```

#### 스프링 표현 언어의 이해

산술, 관계논리, 조건, 정규 표현식 등 사용 가능

``` java
// 이 값은 7이어야 한다
@Value(value = "#{4+3}")
private lateinit var result1 : Number

...

// 이 값은 one.value와 another.value 이어야 한다
@Value(value = "#{ \${one.value} and \${another.value} }")
private lateinit var result4 : Comparable<Boolean>

```

#### 프로파일 사용

프로파일을 변경하면 설절 값을 효과적으로 변경할 수 있다.

##### 프로파일 값 정의

``` yml
spring:
  profiles:
    active: "development"
service:
  message:
    text: "hello"
---
spring:
  profiles: "development"
service:
  message: 
    text: "hi"
---
spring:
  profiles: "production"
service:
  message:
    text: "welcome"
```

spring.profiles.active가 현재 프로파일 설정을 나타낸다. --- 이후의 섹션에서 active profile에 설정한 값을 참고하게 된다.

##### 프로파일을 사용한 실행

기본 값은 development 이므로 "hi"를 가져와서 표시한다.
아래와 같이 하면 다른 프로파일의 설정 값을 읽어서 표시할 수 있고 "welcome"이 표시된다.

```
java -jar target/chapter2-0.0.1-SNAPSHOT.jar --spring.profiles.active="production"
```

#### 조건부 빈 만들기

컴포넌트 스캔을 통한 자동 빈 생성, 이후 빈 인스턴스가 필요하면 @Autowired로 주입하는데
상황에 따라 빈이 주입되는 걸 결정하는 설정이 필요하다.

##### 명시적으로 빈 만들기

기존의 @Service 애노테이션이 있는 부분을 삭제하고 아래와 같이 코드를 작성하면 명시적으로 빈 생성을 할 수 있다.

``` kotlin
@Bean
fun exampleService() : ServiceInterface = ExampleService()
```

##### 추가 빈 정의

AdvanceService 서비스 클래스를 하나 더 추가하고 다음과 같이 빈을 명시적으로 두 개 생성하면 에러가 발생한다.
원하는 종류의 빈 선택을 할 수가 없기 때문이다.

``` kotlin
@Bean
fun exampleService() : ServiceInterface = ExampleService()

@Bean
fun advanceService() : ServiceInterface = AdvanceService()
```

##### 조건으로 빈 정의

SpEL을 사용해 값으로 빈을 로드하도록 수정한다.

``` kotlin
@Bean
@ConditionalOnExpression("#{'\${service.message.type}'=='simple'}")
fun exampleService() : ServiceInterface = ExampleService()

@Bean
@ConditionalOnExpression("#{'\${service.message.type}'=='advance'}")
fun advanceService() : ServiceInterface = AdvanceService()
```

그리고 프로파일 값 수정을 하면 활성화 시킬 서비스 빈을 정의할 수 있다.

``` yml
spring:
  profiles:
    active: "development"
service:
  message:
    type: "simple"
    text: "hello"
---
spring:
  profiles: "development"
service:
  message: 
    text: "hi"
---
spring:
  profiles: "production"
service:
  message:
    type: "advance"
    text: "welcome"
```

##### 다른 설정 실행하기

advance 서비스는 다음과 같이 실행할 수 있다.

```
java -jar target/chapter2-0.0.1-SNAPSHOT.jar --service.message.type="advance"
```

서비스 유형을 지정하지 않고 production 프로파일에서 실행하면 다음과 같이 실행할 수 있다.
production에는 service.message.type이 "advance"이므로 advance 서비스를 로드한다.

```
java -jar target/chapter2-0.0.1-SNAPSHOT.jar --spring.profiles.active="production"
```
