### ISSUE TITLE
6-2 컨피그 서버

### ISSUE THREAD

**Issue by jongfeel** [jongfeel/BookReview#496]
### 6-2 컨피그 서버

컨피그 서버Config Server를 사용하면 모든 마이크로서비스에 필요한 설정을 제공할 수 있기 때문에 마이크로서비스가 시작할 때 컨피그 서버의 위치 이외의 추가 설정은 필요하지 않다. 이런 설정은 파일로 저장하거나 git 저장소 또는 데이터베이스에 이르기 까지 다양한 백엔드를 사용할 수 있다.

컨피그 서버는 애플리케이션 프로파일을 관리할 수 있다. 마이크로서비스를 어떻게 시작하는지에 따라서 다양하게 설정 가능하다. 

#### 컨피그 서버 만들기

스프링 이니셜라이저에서 컨피그 서버를 만들 수 있다.
아래와 같은 설정으로 생성한다.

<img width="983" alt="image" src="https://github.com/jongfeel/BookReview/assets/17442457/00e0b565-ec6a-4746-82da-1bb6b6e332d2">

application.properties를 applycation.yml로 바꾸고 포트를 8888로 설정한다.

``` yml
server:
  prot: 8888
```

gradlew bootrun을 실행하면 아래와 같은 결과를 볼 수 있다.

<img width="1057" alt="image" src="https://github.com/jongfeel/BookReview/assets/17442457/70ae07ff-388b-40d5-9968-292536585add">

@EnableConfigServer 애노테이션을 사용해서 실제 컨피그 서버가 되도록 수정한다.

``` kotlin
@SpringBootApplication
@EnableConfigServer
class Chapter06ConfigserverApplication

fun main(args: Array<String>) {
	runApplication<Chapter06ConfigserverApplication>(*args)
}
```

application.yml을 수정해서 컨피그 서버가 resources 안의 폴더를 사용하도록 설정한다.

``` yml
server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/
```

서버를 재시작 한 후
http://localhost:8888/application/default 를 요청하면 아래와 같이 출력된다.

<img width="385" alt="image" src="https://github.com/jongfeel/BookReview/assets/17442457/b3e8edb2-01fd-4476-8f3f-291977180a07">

/src/main/resources/config/application.yml 경로에 기본 설정을 추가한다.

``` yml
microservices:
  example:
    greetings: "hello"
```

서버 재시작 후 http://localhost:8888/application/default 를 요청하면 추가한 설정 값을 볼 수 있다.

<img width="371" alt="image" src="https://github.com/jongfeel/BookReview/assets/17442457/273941f2-36a3-4682-a607-9ee5ddb86712">

새로운 설정을 가져오지 못한다면
gradlew clean 명령을 통해 캐시 값을 제거한 후 다시 실행하면 된다.
gradlew clean bootrun으로 동시 실행도 가능하다.

#### 설정 얻기

아래와 같은 로그가 보인다는 건 마이크로서비스가 컨피그 서버에 연결해 설정을 검색할 수 있음을 의미한다.

<img width="1069" alt="image" src="https://github.com/jongfeel/BookReview/assets/17442457/4a853517-2d31-41fb-8381-67990949c044">

6-1에서 config client를 추가해서 생성한 프로젝트에 RestController를 추가하고 설정을 가져오는지 확인한다.
GreetingsController 새 클래스 추가

``` kotlin
@RestController
class GreetingsController {

    @Value("\${microservices.example.greetings}")
    private lateinit var greetings: String

    @GetMapping("/greetings")
    fun greetings() = greetings
}
```

이후 config client를 실행해서 http://localhost:8080/greetings 를 요청하면 hello가 출력되는 걸 볼 수 있다.

여기서 @Value에 해당하는 부분이 config server를 통해 컴포넌트 스캔을 하고 bean을 생성해 주입하는 동작을 하므로 만약 config server쪽에 설정한 값의 철자 하나가 틀리면 bean을 생성할 수 없다는 에러를 만나게 된다.

`Error creating bean with name 'greetingsController': Injection of autowired dependencies failed`

실제 경험담으로 책에는 microservice.example.greetings로 되어 있었는데 나의 경우는 s를 더 붙여서 microservices.example.greetings로 했었고 이걸 못찾는 오류를 접해서 몇 시간을 헤맸었다.

config server를 중지하고 resources/config/application.yml 파일을 아래와 같이 편집한다.

```
microservices:
  example:
    greetings: "hello from config server"
```

config server를 재시작 하고 config client도 재시작 한 후에 http://localhost:8080/greetings 를 요청하면 다음의 결과를 볼 수 있다.

<img width="258" alt="image" src="https://github.com/jongfeel/BookReview/assets/17442457/3aa1aea1-80dc-4038-ac63-e874bcfcfdc4">

config server와 client 모두 재시작해야 변경이 반영되는 이유는

- 변경된 설정 값을 가져올 수 있도록 config server를 재시작해야 한다.
- config client를 시작할 때만 설정을 가져오기 때문에 재시작해야 한다.
- config server를 먼저 시작해야만 config client에서 설정을 가져올 수 있다.

```
재시작하지 않고 이 작업을 할 수 있는 방법이 있다.
하지만 내용이 복잡하므로 자세히 살펴 보려면 공식 컨피그 서버 설명서를 보는 게 좋다.
https://docs.spring.io/spring-cloud-config/docs/current/reference/html/
```

config server로 부터 설정을 가져오는 여러 마이크로서비스가 있기 때문에 각 설정을 개별적으로 지정해야 한다.

config client에서 application.properties의 이름을 application.yml로 변경하고 application.name의 값을 입력한다.
이것은 애플리케이션의 이름을 정의한 것이고 컨피그 서버에 설정을 요청할 때 사용한다.

``` yml
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: "greetings"
```

config server 폴더 src/main/resources/config 경로 아래에 새 설정 파일인 greetings.yml 을 추가한다.
그리고 아래의 값을 입력한다.

``` yml
microservices:
  example:
    greetings: "hello for the greetings application"
```

config server 재시작, config client 재시작 후 http://localhost:8080/greetings 를 요청하면 greetings.yml 값을 읽어서 출력한다.

<img width="255" alt="image" src="https://github.com/jongfeel/BookReview/assets/17442457/7bce7dcd-7648-4718-b790-6b83acd716a9">

config server의 http://localhost:8888/greetings/default 를 요청해 보면 두 개의 config yml 설정 값이 있는 걸 확인할 수 있다.

<img width="385" alt="image" src="https://github.com/jongfeel/BookReview/assets/17442457/675446e3-dbeb-4978-a15d-a268507771a9">

기본 application 설정 그리고 greetings라는 config client용 설정 두 개가 있다.
스프링 클라우드 클라이언트는 설정 값을 결합해 검색한다.  이는 모든 마이크로서비스의 기본 값과 특정 마이크로서비스를 위한 개별 값을 정의할 수 있기 때문에 매우 유용하다.

#### 데이터 암호화

민감한 정보도 설정 파일에 저장할 수 있는데 일반 테스트로 표시하는 건 원치 않을 것이다.
스프링 컨피그 서버를 사용하면 설정 파일의 데이터를 암호화 할 수 있게 해준다.

```
JVM에서 데이터 암호화를 위해서는 JAVA_HOME에 lib 폴더의 Java Cryptography Extension (JCE)를 설치해야 할 수 있다.
Java 8은 아래 주소에서 다운로드할 수 있다.
https://www.oracle.com/java/technologies/javase-jce8-downloads.html
``` 

config server에서 main/src/resources 아래에 bootstrap.yml 파일을 추가해서 아래 내용을 입력한다

``` yml
encrypt.key: "this_is_a_secret"
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
```

데이터 암호화를 위한 암호화 키를 지정한다. 이 값은 안전하게 보관해야 한다.
컨피그 서버가 설정을 클라이언트로 전송할 때 암호를 해독하지 않도록 한다. 클라이언트가 받았을 때 해독해야 한다.

메시지를 암호화 하려면 다음과 같은 cURL 요청을 한다.

``` cmd

```
