### ISSUE TITLE
6-4 게이트웨이

### ISSUE THREAD

**Issue by jongfeel** [jongfeel/BookReview#509]
### 6-4 게이트웨이

클라우드 게이트웨이는 애플리케이션 또는 다른 마이크로서비스에서 마이크로서비스를 사용하는 방법을 단순화할 수 있으며, 인스턴스 간에 로드 밸런싱을 수행하고 인스턴스에 접근하는 명확한 메커니즘과 노출 방법을 단순화 할 수 있다.
스프링 클라우드는 넷플릭스 주울Netflix Zuul을 사용해 클라우드 마이크로서비스를 간단한 경로로 액세스할 수 있는 게이트웨이를 만들 수 있다.

주울은 넷플릭스 리본을 사용해 로드 밸런싱을 수행하고 히스트릭스를 사용해 서킷 브레이커를 생성해서, 클라우드에게 마이크로서비스를 위한 게이트웨이를 제공한다.

#### 게이트웨이 만들기

https://start.pring.io 에서 게이트웨어 서버 생성

<img width="1005" alt="image" src="https://github.com/jongfeel/BookReview/assets/17442457/bb73cfd9-953b-451b-a015-d0a13e442c04">

책의 설명과 달리 Dependencies에서 Zuul을 선택할 수가 없어서 빼고 생성

build.gradel.kts 파일에서 다음 dependency를 추가하는데, release 버전이 명시되어 있어야 함

``` gradle
implementation("org.springframework.cloud:spring-cloud-starter-netflix-zuul:2.0.1.RELEASE")
```

https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-netflix-zuul/2.0.1.RELEASE

8080 포트는 사용중이므로 마이크로서비스의 포트는 0으로 수정한다.

``` yml
server:
  port: 0
```

게이트웨이 프로젝트의 이름을 설정해 준다.

``` yml
spring:
  application:
    name: "gateway"
```

서비스 실행 순서

- Config
- Discovery
- Microservice
- Gateway

막상 실행해 보면 config server를 설정하라고 나오는데 yml 파일에 config server를 설정해 준다.

``` yml
spring:
  config:
    import:
      configserver:http://localhost:8888
```

그러면 http://localhost:8761 에서 유레카 대시보드에서 확인할 수 있다.

<img width="1110" alt="image" src="https://github.com/jongfeel/BookReview/assets/17442457/5aef6407-aa1b-4b60-bdb5-18817a98f61c">

#### 라우터 정의

게이트웨이를 통해 서비스를 라우팅할 수 있다.
Application 클래스에 @EnableZuulProxy 애노테이션을 추가한다.

``` kotlin
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.cloud.netflix.zuul.EnableZuulProxy

@SpringBootApplication
@EnableZuulProxy
class Chapter06GatewayApplication

fun main(args: Array<String>) {
	runApplication<Chapter06GatewayApplication>(*args)
}
```

http://localhost:8080/greetings를 요청하면 마이크로서비스 쪽으로 리다이렉팅 되서 표시된다.

주울은 유레카에 등록된 경로로 리디렉션하는 대신 고유 경로를 정의할 수 있다.

컨피그 서버에서 config/gateway.yml이라는 새 설정파일을 만든다.

``` yml
zuul:
  ignoredServices: '*'
  routes:
    greetings:
      path: /message/**
      serviceId: greetings
```

컨피그 서버와 게이트웨이를 재시작한 후에 http://localhost:8080/message/greegins를 요청하면 greetings 메시지가 표시된다.
